# Generated by Django 5.2.7 on 2025-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('high', 'high')], default=False, max_length=30),
        ),
    ]
